### ISSUE TITLE
[Proposta] Comentários Disqus

### ISSUE THREAD

**Issue by vluzrmos** [artesaos/laravel-docs#26]
Adicionar comentários Disqus em cada página do site da documentação.

**Comment by vitorarjol** [comment]
Eu prefiro uma abordagem diferente: Ao invés de comentários, poderíamos colocar dados adicionais na documentação, de acordo com nossas experiências, aumentando os exemplos e etc. 

Como funcionaria: Ao ver a possibilidade de melhorar a documentação, cria uma issue aqui, debate-se sobre o tema e a pessoa escreve sobre isso pra enviar uma PR. Com um esquema desse a gente poderia até contribuir com a documentação oficial, já que seria só traduzir essa nova parte para o inglês e enviar uma PR.

**Comment by vinicius73** [comment]
Acho as duas idéias muito boas

**Comment by vluzrmos** [comment]
Olá @VitorArjol , isso foi discutido ontem no slack, um erro...
Nós decidimos que cada um pode adicionar extras na documentação, mas não ao ponto de fugir muito do original, apenas adicionar informações que podem ajudar no entendimento da doc em si.

**Comment by vitorarjol** [comment]
Opa! Ai sim :+1:. Minha participação no slack é baixa, vou tentar logar mais lá pra ficar ligado nisso. Taca le pau nos comentários então. Vai ter muita gente que vai comentar lá e não vai olhar no github mesmo auhuhauahhua.

**Comment by frenetic** [comment]
Chegando atrasado, visto que já foi decidido por vocês no Slack.

Acredito que a melhor opção seria traduzir a documentação, de forma fiel.
Se houver necessidade de adicionar coisas novas, primeiro contribui com isso no Laravel-docs original. Se for aceito, adiciona o item pra tradução.

Ou então, se forem fazer adaptações e não querem submeter o mesmo para a documentação original do Laravel, utilizem BLOCKQUOTES, para avisar que aquela parte é coisa nossa, e não da documentação original.

**Comment by fabyo** [comment]
:+1:, acho legal a ideia dos comentarios, e os extras tbm nao precisa ser tao fiel quanto melhor o entendimento para nossa comunidade melhor

**Comment by vitorarjol** [comment]
Acho que o problema nem é não submeter a melhoria, é o Taylor aceitar a alteração. Concordo com uma forma de dizermos que aquela adição em específico não está na doc original, mas acho que poderíamos (pra não dizer deveríamos) melhorar a documentação :)

**Comment by vluzrmos** [comment]
Sobre os comentários na documentação, acabei de implementar.... podem
conferir em http://laravel-docs.artesaos.org/docs/master

**Comment by hernandev** [comment]
``` php
'documentação' != 'forum'; // true
```

**Comment by valdirsjr** [comment]
Muito legal a idéia de complementar a documentação, mas na minha opinião acho importante manter uma referência sólida, que é a documentação oficial do Laravel, em pt-BR, da forma como ela foi concebida. Comentários na mesma página leva a crer que faz parte da documentação, o que não é verdade. Assim como, eventualmente pessoas podem colocar coisas equivocadas, contornos ou críticas, o que também não vem ao caso. Pode ter uma outra página, separado, e um link referenciando ela na documentação, como um "saiba mais" específico da comunidade brasileira.

**Comment by vluzrmos** [comment]
:+1:

**Comment by frenetic** [comment]
+1 @valdirsjr 

Como eu disse antes:

> Acredito que a melhor opção seria traduzir a documentação, de forma fiel.
> Se houver necessidade de adicionar coisas novas, primeiro contribui com isso no Laravel-docs original. Se for aceito, adiciona o item pra tradução.

**Comment by hernandev** [comment]
@frenetic is alive!

**Comment by fhferreira** [comment]
@frenetic :D 

`Acredito que a melhor opção seria traduzir a documentação, de forma fiel.`
